### ISSUE TITLE
rethink `cassandra-launcher` approach

### ISSUE THREAD

**Issue by raboof** [apache/pekko-persistence-cassandra#192]
We're using `sbt-assembly` in an unusual way for cassandra-launcher - I'm not sure `sbt-assembly` really promised to do what we ask it to do here.

This causes trouble trying to update of `sbt-multi-jvm` or `sbt-assembly`.

**Comment by raboof** [comment]
hmm, this still seems to be brittle, breaking the build when plugins change (e.g. #205)

**Comment by Roiocam** [comment]
After some digging out in #206, `cassandra-launcher` has no users to `sbt-assembly`, but `cassandra-bundle` is used.

I think the  `sbt-assembly` usage was in the "box", but the `launcher`build was a little problem.

Based on document: [https://www.scala-sbt.org/1.x/docs/ Classpaths.html# Unmanaged+vs+managed
](https://www.scala-sbt.org/1.x/docs/Classpaths.html#Unmanaged+vs+managed), Maybe we don't need to manage uber jar in the build
